apiVersion: v1
kind: Service
metadata:
  name: kibana-nodeport-service
spec:
  selector:
    app: kibana
  type: NodePort
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30020