elasticsearch:
  clusterName: "graylog"
  fullnameOverride: elastic
  # Change it in multi-node cluster
  replicas: 1
  minimumMasterNodes: 1
  # Change it to "hard" in production
  antiAffinity: "soft"
  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "openebs-hostpath"
    resources:
      requests:
        storage: 8Gi
  extraEnvs:
    - name: "xpack.security.enabled"
      value: "true"
    - name: "xpack.security.transport.ssl.enabled"
      value: "true"
  envFrom:
    - secretRef:
        name: elastic-secret
  # Shrink default JVM heap.
  esJavaOpts: "-Xmx128m -Xms128m"
  # Allocate smaller chunks of memory per pod.
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "512M"
